# Makefile for BCPL/doc

PREFIX?=/usr/local

all:

install:
	mkdir -p $(PREFIX)/share/doc/BCPL
	install -c -m 444 manual.txt   $(PREFIX)/share/doc/BCPL
	install -c -m 444 standard.txt $(PREFIX)/share/doc/BCPL

clean:
