# Makefile for obcpl/doc

PREFIX?=/usr/local

all:

install:
	mkdir -p $(PREFIX)/share/doc/obcpl
	install -c -m 444 manual.txt   $(PREFIX)/share/doc/obcpl
	install -c -m 444 standard.txt $(PREFIX)/share/doc/obcpl

clean:
