# Makefile for bcplc/doc

PREFIX?=/usr/local

all:

install:
	mkdir -p $(PREFIX)/share/doc/bcplc
	install -c -m 444 manual.txt   $(PREFIX)/share/doc/bcplc
	install -c -m 444 standard.txt $(PREFIX)/share/doc/bcplc

clean:
